src/Entity/Decision.php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DecisionRepository")
 */
class Decision
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $AlarmStichwort;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $ort;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $bemerkung;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $decision;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAlarmStichwort(): ?string
    {
        return $this->AlarmStichwort;
    }

    public function setAlarmStichwort(string $AlarmStichwort): self
    {
        $this->AlarmStichwort = $AlarmStichwort;

        return $this;
    }

    public function getOrt(): ?string
    {
        return $this->ort;
    }

    public function setOrt(string $ort): self
    {
        $this->ort = $ort;

        return $this;
    }

    public function getBemerkung(): ?string
    {
        return $this->bemerkung;
    }

    public function setBemerkung(string $bemerkung): self
    {
        $this->bemerkung = $bemerkung;

        return $this;
    }

    public function getDecision(): ?string
    {
        return $this->decision;
    }

    public function setDecision(string $decision): self
    {
        $this->decision = $decision;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Models\Einsatz;
use App\Repository\EinsatzRepository;
use App\Service\Validator\Decider;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

final class HomeController extends AbstractController
{
    private EinsatzRepository $einsatzRepository;
    private Decider $decider;

    public function __construct(EinsatzRepository $einsatzRepository, Decider $decider)
    {
        $this->einsatzRepository = $einsatzRepository;
        $this->decider = $decider;
    }

    /**
     * @Route("/", name="home")
     */
    public function index(): Response
    {
        $einsaetze = $this->einsatzRepository->getOffeneEinsaetze();

        $models = [];
        foreach ($einsaetze as $einsatz) {
            $desicion = $this->decider->decide($einsatz);
            $models[] = Einsatz::create($desicion, $einsatz);
        }

        return $this->render('home/index.html.twig', [
            'einsaetze' => $models,
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fire Wire | Einsätze{% endblock %}

{% block navbar %}
    {% include "home/navbar.html.twig" %}
{% endblock %}

{% block body %}
    
    <table class="table table-hover table-responsive-sm">
        <thead>
            <tr>
                <th scope="col">Einsatznummer</th>
                <th scope="col">Einsatzstichwort</th>
                <th scope="col">Meldebild</th>
                <th scope="col">Bemerkung</th>
                <th scope="col">Ort</th>
                <th scope="col">Objekt</th>
                <th scope="col">Einsatzmittel</th>
                <th scope="col">Alamierungszeit</th>
                <th scope="col">Status</th>
            </tr>
        </thead>
        <tbody>
        {% for einsatz in einsaetze %}
            <tr>
                <td>{{ einsatz.einsatznummer }}</td>
                <td>{{ einsatz.alarmStichwort }}</td>
                <td>{{ einsatz.meldebild }}</td>
                <td>{{ einsatz.bemerkung }}</td>
                <td>{{ einsatz.strasse }}</td>
                <td>{{ einsatz.objekt }}</td>
                <td>{{ einsatz.einsatzmittel }}</td>
                <td>{{ einsatz.alamierungszeit|date("d.m.Y h:m:s") }}</td>
                <td>
                {% if einsatz.status == 'offen' %}
                    <span class="badge badge-primary">{{ einsatz.status }}</span>
                {% else %}
                    <span class="badge badge-dark">{{ einsatz.status }}</span>
                {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/home/navbar.html.twig
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ path('home') }}">Fire Wire</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ path('dashboard') }}">Admin <span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
</nav>